### ISSUE TITLE
Credential not found for adapter when using middleware

### ISSUE THREAD

**Issue by rmoreno123** [gnk-softworks/lucia-dynamodb-adapter#2]
I am working with the dynamoDB adapter for my NextJS application which seems to be working as expected for logging sessions and creating users in my database. My error occurs when I try to utilize lucia functions such as `.validateSession()` in my middleware file. I seem to get this error:

```
 Error: Credential is missing
    at eval (webpack-internal:///(middleware)/./node_modules/@aws-sdk/client-dynamodb/dist-es/runtimeConfig.browser.js:37:102)
    at eval (webpack-internal:///(middleware)/./node_modules/@smithy/core/dist-es/middleware-http-auth-scheme/httpAuthSchemeMiddleware.js:37:29)
    at async eval (webpack-internal:///(middleware)/./node_modules/@aws-sdk/middleware-logger/dist-es/loggerMiddleware.js:9:26)
    at async DynamoDBAdapter.getSession (webpack-internal:///(middleware)/./node_modules/lucia-dynamodb-adapter/dist/index.js:56:26)    
    at async DynamoDBAdapter.getSessionAndUser (webpack-internal:///(middleware)/./node_modules/lucia-dynamodb-adapter/dist/index.js:39:25)
    at async Lucia.validateSession (webpack-internal:///(middleware)/./node_modules/lucia/dist/core.js:68:49)
    at async Object.middleware [as handler] (webpack-internal:///(middleware)/./src/middleware.js:28:25)
    at async adapter (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:179:16)
    at async (file://C:\...\node_modules\next\dist\server\web\sandbox\sandbox.js:110:22)
    at async runWithTaggedErrors (file://C:\...\node_modules\next\dist\server\web\sandbox\sandbox.js:107:9)
```

My middleware file looks something like this, where I am trying to do a session validation using the lucia object defined in my /libs directory:

```
export async function middleware(request) {
  const sessionId = cookies().get(lucia.sessionCookieName)?.value ?? null;
  const { session } = await lucia.validateSession(sessionId) ?? null;                               // Error occurs on this line
}
```

I believe it has something to do with the adapter as I am able to connect to my dynamoDB just fine when my middlware file is empty. I have tested this by making multiple requests to my database from my application and can confirm I have valid credentials via the Amazon SDK. Is there something I may be missing that leads to this error?  I have defined an auth.ts file similar to the lucia docs and defined my adapter as it shows on the quickstart guide (README.md) found on the repo. Any help would be greatly appreciated.

**Comment by CarlRobinsonRAM** [comment]
I believe this is an AWS Credential issue where the DynamoDB client you are creating and then passing into this adapter doesn't have the credentials set. 

The example in the readme is for an app where the IAM role or credentials are set at a system level where the SDK can pick it up automatically. If this is not the case you will need to pass them in when creating the client. See below:

`const client = new DynamoDBClient({
    credentials: {
        accessKeyId: "YOUR_ACCESS_KEY_ID",
        secretAccessKey: "YOUR_ACCESS_KEY_SECRET",
    }
});

const adapter = new DynamoDBAdapter({
    client,
    sessionTableName: "YOUR_SESSION_TABLE,
    sessionUserIndexName: "YOUR_USER_INDEX",
    getUser: yourGetUserFunction()
});`

If this is not your issue or you need more help please provide:
1. The code you are using to create the client and pass it into the adapter 
2. Some more context around where you are hosting, where you iam credentials are coming from, how your other dynamodb client is set up.

**Comment by Kawba** [comment]
I believe this is an AWS Credential issue where the DynamoDB client you are creating and then passing into this adapter doesn't have the credentials set.

The example in the readme is for an app where the IAM role or credentials are set at a system level where the SDK can pick it up automatically. If this is not the case you will need to pass them in when creating the client. See below:

```
const client = new DynamoDBClient({
    credentials: {
        accessKeyId: "YOUR_ACCESS_KEY_ID",
        secretAccessKey: "YOUR_ACCESS_KEY_SECRET",
    }
});

const adapter = new DynamoDBAdapter({
    client,
    sessionTableName: "YOUR_SESSION_TABLE,
    sessionUserIndexName: "YOUR_USER_INDEX",
    getUser: yourGetUserFunction()
});
```

If this is not your issue or you need more help please provide:
1. The code you are using to create the client and pass it into the adapter (Your auth.ts file but omit any sensitive info)
2. Some more context around where you are hosting, where you iam credentials are coming from, how your other dynamodb client is set up.

**Comment by Kawba** [comment]
Hope this solved your problem! I'm going to close this issue. If the problem remains, please create another issue and I'll be happy to help!
